"""Shared accessibility query limits without GUI dependencies."""

DEFAULT_MAX_DEPTH = 8
MAX_DEPTH = 64
DEFAULT_MAX_NODES = 256
MAX_NODES = 4096
DEFAULT_MATCH_LIMIT = 20
MAX_MATCH_LIMIT = 100
DEFAULT_INSPECT_TIMEOUT = 5.0
DEFAULT_CHECK_TIMEOUT = 2
MAX_TIMEOUT = 10
MAX_TEXT_LENGTH = 1024
